### ISSUE TITLE
SVG Version

### ISSUE THREAD

**Issue by danmilon** [shigeki/node-class-diagram#1]
Hello,

Thank you for that contribution! I think it makes it much easier (especially for these kind of images) to be vectors. Could you generate an SVG version? Might as well consider having that as primary.

Thanks,
danmilon..

**Comment by shigeki** [comment]
Thanks for your request. I've just added the svg version.

**Comment by innos123** [comment]
> Hello,
> 
> Thank you for that contribution! I think it makes it much easier (especially for these kind of images) to be vectors. Could you generate an SVG version? Might as well consider having that as primary.
> 
> Thanks, danmilon..

**Comment by innos123** [comment]
- [ ]

**Comment by innos123** [comment]
> * [ ]

- [ ]

**Comment by innos123** [comment]
-

>  #`
Duplicate of   ### 

- 

- 

- _**@@#

1. 

- [ ] []() 

`**_

**Comment by innos123** [comment]
> Thanks for your request. I've just added the svg version.

















> Hello,
> 
> Thank you for that contribution! I think it makes it much easier (especially for these kind of images) to be vectors. Could you generate an SVG version? Might as well consider having that as primary.
> 
> Thanks, danmilon..

**Comment by innos123** [comment]
> Hello,
> 
> Thank you for that contribution! I think it makes it much easier (especially for these kind of images) to be vectors. Could you generate an SVG version? Might as well consider having that as primary.
> 
> Thanks, danmilon..
